
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=4992663gulnare

spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

jwt.secret=SUPER_SECRET_KEY_123_SUPER_SECRET_KEY_456
jwt.expirationMillis=3600000
jwt.refreshExpirationMillis=1209600000


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gulnareislamova63@std.beu.edu.az
spring.mail.password=deej wlhv ebaj lmiv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




